### ISSUE TITLE
Bad detection of Chrome Mobile

### ISSUE THREAD

**Issue by barbiedrummer** [51Degrees/device-detection-go#5]
We are using Enterprise-HashV41.hash with golang library. 

Latest db (3/21/2022) detects property BrowserName of user-agent `Mozilla/5.0 (Linux; Android 11; RMX3261) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.46 Mobile Safari/537.36` as "Chrome".

But on https://51degrees.com/developers/user-agent-tester the same ua is detected as "Chrome Mobile". 

As we suggest there is some problem with detection in Enterprise-HashV4 db.

**Comment by krpn** [comment]
@jwrosewell, which algorithm is used by user-agent tester page?

**Comment by jwrosewell** [comment]
Predictive. See the Device Metrics page.

![image](https://user-images.githubusercontent.com/1679482/159327827-0854e40c-dd80-4fb6-bcb2-bfdcdb1a5ce0.png)

**Comment by krpn** [comment]
@jwrosewell, thank you. Setting predictive doesn't help:

![image](https://user-images.githubusercontent.com/16793635/159329434-494c7953-a63e-49cd-b313-5bd6f47d6489.png)

Database version: 3/21/2022

Does user-agent tester database have the same version?

**Comment by jwrosewell** [comment]
Reopening as there is now evidence this could relate to the go API.

Could you you also add the following line to the config.

```Go
config.SetUsePerformanceGraph(false)
````

**Comment by krpn** [comment]
@jwrosewell, added. Nothing is changed.

**Comment by jwrosewell** [comment]
Thanks. We'll triage in the next week and let you know what we find.

**Comment by krpn** [comment]
@jwrosewell, thank you. Very much looking forward to. Now will rollback to one week for datafile.

**Comment by krpn** [comment]
It worked correctly on `3/15/2022` datafile.

**Comment by tungntpham** [comment]
@krpn,

Thanks for the update. We can confirm that this can be reproduced in our environment. We will investigate and keep you updated.

Tung.

**Comment by krpn** [comment]
@tungntpham @jwrosewell looking fiexd in `3/24/2022`. Output now:

```
Chrome Mobile <nil>
3
```

**Comment by bziaks** [comment]
Similar issue here with Chrome and Chrome Mobile: enterprise-db (3/29/2022) detects UA `Mozilla/5.0 (Linux; Android 11; SM-A515F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.88 Mobile Safari/537.36` as `Chrome` if we use Client Hints and as `Chrome Mobile` if we use only User-Agent for detection. OS is `Android` in both cases.

**Comment by Steve51D** [comment]
Thanks @bziaks,

Currently, our product does not have 'full' support for User Agent Client Hints. This is mainly due to the changes that kept being made to the UA-CH specification and lack of clarity around the timetable.
This means that the results when using UA-CH values with the current data files and API can be less than ideal.

However, we are now close to rolling out both API updates and data files that will work fully with UA-CH.
We plan on the API version that fully supports UA-CH being 4.4. 
We're not certain on the date of the first data files yet, but expect those to be available for testing in the next week or so, and to replace the current data files in production within a few more weeks.

To be clear, older API versions and data file versions can still be used, and are cross compatible with each other. It's just that to get the best results, we will recommend using version 4.4 of the API along with the most recent data files.

**Comment by krpn** [comment]
Any progress with this? :)

**Comment by Steve51D** [comment]
Yes, we're actually just preparing an update to go out to all customers on this.

Version 4.4.x of the API has been available for a few days and the updated data files are now being made available on request.
I'll update here once I have more details.

**Comment by krpn** [comment]
@Steve51D, thank you very much!

**Comment by Steve51D** [comment]
The updated v4 (hash) data files have been live on our cloud service for about a month now and have now replaced the previous ones in all scenarios. These will be picked up as part of your existing automatic update process.

To manually download the latest files, see http://51degrees.com/developers/downloads/enhanced-device-data

Please let us know if you experience any issues.
